spring.application.name=producer
#spring.kafka.producer.bootstrap-servers=localhost:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.producer.properties.spring.json.add.type.headers=false

#spring.application.name=producer

spring.cloud.function.definition=sendRiderLocation

spring.cloud.stream.function.definition=sendRiderLocation

spring.cloud.stream.bindings.sendRiderLocation-out-0.destination=new-topic
spring.cloud.stream.bindings.sendRiderLocation-out-0.content-type=application/json

spring.cloud.stream.kafka.binder.brokers=localhost:9092